### PR TITLE
Edited readme.md for clarification

### PR DESCRIPTION
**Pull request by bkrmendy**

### CODE REVIEW

**Comment by hnes** [comment]
Thank you very much, @bkrmendy.

Please give me some time to read it all carefully.

**Comment by zii** [comment]
He is so sweet. 😄

**Comment by hnes** [comment]
I also like this PR, and I am reading it :D

**Comment by hnes** [comment]
Hi, @bkrmendy, I'm sorry it has been taken so long to be merged (most of its parts are merged).

New PR is still welcome if you find something wrong in this project. Thank you very much for your elaborative contribution :D

**Comment by hnes** [comment]
Most of the parts in this PR are merged. Thank you for your contribution ;-)

**Comment by bkrmendy** [comment]
Thanks, next time i hope i'll be able to touch the code too 😅

**Comment by hnes** [comment]
Look forward to your next excellent contribution :D 

libaco is an open-sourced project, thus it belongs to every one of us ;-)

**Pull request closed without merging**
